'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Mail, Lock, Loader2, AlertCircle, Eye, EyeOff, CheckCircle2, Circle } from 'lucide-react';
import { registerUser } from '@/lib/strapi';

export default function RegisterPage() {
    const router = useRouter();
    const [formData, setFormData] = useState({
        username: '',
        email: '',
        password: '',
    });
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [showPassword, setShowPassword] = useState(false);
    const [isPasswordFocused, setIsPasswordFocused] = useState(false);

    //Password Requirements Checklist
    const requirements = [
        { label: 'Mínimo 8 caracteres', test: (p: string) => p.length >= 8 },
        { label: 'Una letra mayúscula', test: (p: string) => /[A-Z]/.test(p) },
        { label: 'Un número', test: (p: string) => /[0-9]/.test(p) },
        { label: 'Un carácter especial', test: (p: string) => /[^A-Za-z0-9]/.test(p) },
    ];

    const isPasswordSecure = requirements.every(req => req.test(formData.password));

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!isPasswordSecure) {
            setError('Por favor cumple con todos los requisitos de seguridad');
            return;
        }

        setLoading(true);
        setError(null);

        const emailPrefix = formData.email.split('@')[0];
        const randomSuffix = Math.floor(1000 + Math.random() * 9000);
        const autogeneratedUsername = `${emailPrefix}_${randomSuffix}`.replace(/[^a-zA-Z0-9]/g, '_');

        try {
            const data = await registerUser(autogeneratedUsername, formData.email, formData.password);
            localStorage.setItem('jwt', data.jwt);
            localStorage.setItem('user', JSON.stringify(data.user));
            router.push('/dashboard');
        } catch (err: any) {
            setError(err.message || 'Error en el registro');
        } finally {
            setLoading(false);
        }
    };

    return (
        <>
            <div className="text-center mb-8">
                <h1 className="text-4xl font-bold bg-gradient-to-r from-white to-slate-400 bg-clip-text text-transparent mb-2">
                    Crear Cuenta
                </h1>
                <p className="text-slate-400">Únete a nuestra plataforma premium</p>
            </div>

            {error && (
                <div className="bg-red-500/10 border border-red-500/20 text-red-300 p-3 rounded-lg text-sm mb-5 flex items-center gap-2">
                    <AlertCircle size={18} />
                    <span>{error}</span>
                </div>
            )}

            <form className="flex flex-col gap-5" onSubmit={handleSubmit} autoComplete="off">
                <div className="flex flex-col gap-2">
                    <label htmlFor="email" className="text-sm font-medium text-slate-200 ml-1">
                        Correo electrónico
                    </label>
                    <div className="relative flex items-center">
                        <Mail size={20} className="absolute left-3.5 text-slate-400" />
                        <input
                            type="email"
                            id="email"
                            name="email-field-random-id"
                            placeholder="tu@email.com"
                            className="input-field"
                            value={formData.email}
                            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                            autoComplete="off"
                            required
                        />
                    </div>
                </div>

                <div className="flex flex-col gap-2">
                    <label htmlFor="password" className="text-sm font-medium text-slate-200 ml-1">
                        Contraseña
                    </label>
                    <div className="relative flex items-center">
                        <Lock size={20} className="absolute left-3.5 text-slate-400" />
                        <input
                            type={showPassword ? "text" : "password"}
                            id="password"
                            name="password-field-random-id"
                            placeholder="Crea una contraseña segura"
                            className="input-field"
                            value={formData.password}
                            onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                            onFocus={() => setIsPasswordFocused(true)}
                            onBlur={() => setIsPasswordFocused(false)}
                            autoComplete="new-password"
                            required
                        />
                        <button
                            type="button"
                            className="absolute right-3.5 text-slate-400 hover:text-white transition-colors"
                            onClick={() => setShowPassword(!showPassword)}
                        >
                            {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                        </button>
                    </div>

                    {/* Password Strength Checklist - Conditional Rendering */}
                    {(isPasswordFocused || formData.password.length > 0) && !isPasswordSecure && (
                        <div className="mt-2 space-y-2 bg-white/5 p-4 rounded-xl border border-white/5 animate-in fade-in slide-in-from-top-2 duration-300">
                            <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Requisitos de seguridad:</p>
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                                {requirements.map((req, idx) => {
                                    const isMet = req.test(formData.password);
                                    return (
                                        <div key={idx} className={`flex items-center gap-2 text-xs transition-colors duration-300 ${isMet ? 'text-emerald-400' : 'text-slate-500'}`}>
                                            {isMet ? <CheckCircle2 size={14} /> : <Circle size={14} />}
                                            <span>{req.label}</span>
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    )}
                </div>

                <button
                    type="submit"
                    className={`btn-primary ${(!isPasswordSecure || loading) ? 'opacity-50 cursor-not-allowed' : ''}`}
                    disabled={loading || !isPasswordSecure}
                >
                    {loading ? <Loader2 className="animate-spin" /> : 'Registrarse'}
                </button>
            </form>

            <div className="text-center mt-6 text-slate-400 text-sm">
                ¿Ya tienes una cuenta? <Link href="/login" className="text-indigo-400 font-semibold hover:underline">Inicia sesión</Link>
            </div>
        </>
    );
}
