'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Mail, Lock, Loader2, AlertCircle, Eye, EyeOff, CheckCircle2, Circle, Check } from 'lucide-react';
import { registerUser } from '@/lib/strapi';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { toast } from 'sonner';

export default function RegisterPage() {
    const router = useRouter();
    const [formData, setFormData] = useState({
        username: '',
        email: '',
        password: '',
    });
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [showPassword, setShowPassword] = useState(false);
    const [isPasswordFocused, setIsPasswordFocused] = useState(false);

    // Password Requirements Checklist
    const requirements = [
        { label: 'Una letra mayúscula', test: (p: string) => /[A-Z]/.test(p) },
        { label: 'Una letra minúscula', test: (p: string) => /[a-z]/.test(p) },
        { label: 'Un número', test: (p: string) => /[0-9]/.test(p) },
        { label: 'Un carácter especial (ej. !?<>@#$%)', test: (p: string) => /[^A-Za-z0-9]/.test(p) },
        { label: '8 caracteres o más', test: (p: string) => p.length >= 8 },
    ];

    const isPasswordSecure = requirements.every(req => req.test(formData.password));

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!isPasswordSecure) {
            setError('Por favor cumple con todos los requisitos de seguridad');
            toast.warning('Requisitos de contraseña insuficientes');
            return;
        }

        setLoading(true);
        setError(null);

        const emailPrefix = formData.email.split('@')[0];
        const randomSuffix = Math.floor(1000 + Math.random() * 9000);
        const autogeneratedUsername = `${emailPrefix}_${randomSuffix}`.replace(/[^a-zA-Z0-9]/g, '_');

        try {
            const data = await registerUser(autogeneratedUsername, formData.email, formData.password);
            localStorage.setItem('jwt', data.jwt);
            localStorage.setItem('user', JSON.stringify(data.user));
            toast.success('¡Registro completado con éxito!');
            router.push('/dashboard');
        } catch (err: any) {
            setError(err.message || 'Error en el registro');
            toast.error('Error al crear la cuenta');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="flex flex-col gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex flex-col items-center text-center">
                <h1 className="text-2xl font-bold">
                    Crear Cuenta
                </h1>
                <p className="text-balance text-muted-foreground">
                    Únete a nuestra plataforma premium
                </p>
            </div>

            {error && (
                <Alert variant="destructive" className="animate-in fade-in zoom-in duration-300">
                    <AlertCircle className="h-4 w-4" />
                    <AlertTitle>Error</AlertTitle>
                    <AlertDescription>{error}</AlertDescription>
                </Alert>
            )}

            <form className="grid gap-6" onSubmit={handleSubmit} autoComplete="off">
                <div className="grid gap-2">
                    <label htmlFor="email" className="text-sm font-medium leading-none">
                        Correo electrónico
                    </label>
                    <div className="relative">
                        <Mail size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
                        <Input
                            id="email"
                            type="email"
                            placeholder="tu@email.com"
                            className="pl-10 h-11"
                            value={formData.email}
                            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                            autoComplete="off"
                            required
                        />
                    </div>
                </div>

                <div className="grid gap-2">
                    <label htmlFor="password" className="text-sm font-medium leading-none">
                        Contraseña
                    </label>
                    <div className="relative">
                        <Lock size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
                        <Input
                            id="password"
                            type={showPassword ? "text" : "password"}
                            placeholder="Crea una contraseña segura"
                            className="pl-10 pr-10 h-11"
                            value={formData.password}
                            onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                            onFocus={() => setIsPasswordFocused(true)}
                            onBlur={() => setIsPasswordFocused(false)}
                            autoComplete="new-password"
                            required
                        />
                        <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            className="absolute right-1 top-1/2 -translate-y-1/2 h-8 w-8 text-muted-foreground hover:text-foreground"
                            onClick={() => setShowPassword(!showPassword)}
                        >
                            {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                        </Button>
                    </div>

                    {/* Password Strength Checklist */}
                    {(isPasswordFocused || formData.password.length > 0) && !isPasswordSecure && (
                        <div className="mt-4 space-y-2 lg:space-y-3 animate-in fade-in slide-in-from-top-2 duration-300 transform-gpu">
                            {requirements.map((req, idx) => {
                                const isMet = req.test(formData.password);
                                return (
                                    <div
                                        key={idx}
                                        className={`flex items-center gap-2 text-xs transition-all duration-300 ${isMet ? 'text-primary font-medium translate-x-1' : 'text-muted-foreground'
                                            }`}
                                    >
                                        <div className={`
                                            flex items-center justify-center w-4 h-4 rounded-full border transition-all duration-300
                                            ${isMet
                                                ? 'bg-primary border-primary text-primary-foreground'
                                                : 'border-muted-foreground/30 bg-transparent'
                                            }
                                        `}>
                                            {isMet && <Check size={10} strokeWidth={3} className="animate-in zoom-in duration-300" />}
                                        </div>
                                        <span>{req.label}</span>
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </div>

                <Button
                    type="submit"
                    className="w-full h-11 text-base font-semibold"
                    disabled={loading || !isPasswordSecure}
                >
                    {loading ? (
                        <>
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                            Creando cuenta...
                        </>
                    ) : 'Registrarse'}
                </Button>
            </form>

            <div className="text-center text-sm text-balance">
                ¿Ya tienes una cuenta?{' '}
                <Link href="/login" className="underline underline-offset-4 hover:text-primary">
                    Inicia sesión
                </Link>
            </div>
        </div>
    );
}
